# Generated by Django 3.2.22 on 2023-11-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_1', models.TextField()),
                ('heading_2', models.TextField()),
                ('image', models.ImageField(upload_to='hero')),
            ],
        ),
    ]
