# Generated by Django 3.2.22 on 2023-11-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='heading_1',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='heading_2',
        ),
        migrations.AddField(
            model_name='herosection',
            name='text1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='herosection',
            name='text2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
