# Generated by Django 3.2.22 on 2023-11-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20231120_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subheadiing', models.CharField(default='subheading', max_length=100)),
                ('h2', models.CharField(default='heading 2', max_length=150)),
                ('text', models.TextField(default='text')),
                ('text2', models.CharField(max_length=100)),
            ],
        ),
    ]
