# Generated by Django 3.2.22 on 2023-11-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20231121_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(default='', max_length=50)),
                ('text', models.TextField(default='text')),
                ('image', models.ImageField(upload_to='testimonials')),
            ],
        ),
    ]
