# Generated by Django 3.2.22 on 2023-11-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
