# Generated by Django 3.2.22 on 2023-11-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_booked',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='check_in',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='check_out',
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
